source 'https://github.com/CocoaPods/Specs.git'
platform :ios, :deployment_target => '7.0'

pod 'PureLayout'
pod 'FrameAccessor'
pod 'AFNetworking', '2.5.4'
pod 'SVProgressHUD'
pod 'IQKeyboardManager', '3.2.4'
pod 'UIActionSheet+Blocks', '0.8.1'
pod 'UIAlertView+Blocks', '0.8.1'
pod 'SSKeychain'